In Native python, lists can be thought of as arrays, however in general array has one data type only. Lists can have multiple data types.

In [1]:
# Creating a list of weights of 5 people
weight=[40,30,89,43,43]

In [2]:
# Creating a list of heights of 5 people
height=[110,165,143,187,98]

In [5]:
# Suppose we want to find the ratio of height:weight for these people , how can we do this?
height/weight

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [8]:
# However, we can do this using the list.append method
r=[]
for i in range(len(weight)):
    t=height[i]/weight[i]
    r.append(t)

In [9]:
r

[2.75, 5.5, 1.6067415730337078, 4.348837209302325, 2.2790697674418605]

To get around this, we have a core library called Numpy for data manipulation
Numpy has the following advantages over lists:

1. FASTER: They are faster than lists
2. Size: They take up less space
3. Functions :They have built in functions which make data manipulations very easy.

However, they have only 1 data type.

The general form of a numpy array is np.array(data,datatype)


In [10]:
import numpy as np

In [24]:
w=np.array(weight,dtype='int32')
h=np.array(height,dtype='int32')

In [129]:
a=h/w
a

array([2.75      , 5.5       , 1.60674157, 4.34883721, 2.27906977])

Some characteristics of the numpy array are:
1. Type
2. length
3. Dimension
4. Data type
5. Size

In [29]:
# type of this numpy array
type(a)

numpy.ndarray

In [18]:
## dimension of numpy array
a.ndim

1

In [22]:
# Length of numpy array
len(a)

5

In [38]:
a.dtype

dtype('float64')

In [130]:
a.size

5

In [132]:
# We can also find the max and min value
print(a.max())
print(a.min())

5.5
1.6067415730337078


For all the methods associated with the numpy array press tab after the object

In [229]:
#How to create a  2d array

twod=np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])

In [94]:
print(twod)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [48]:
# The tuple (m,n ) in case of a shape of a 2d array can be thought of as rows and columns.
# however, this kind of naming convention gets difficult to comprehend in case of higher dimensioons
twod.shape

(3, 4)

# INDEXING THE ARRAYS
It follows the same logic as we discussed in lists

In [232]:
# Indexing a one d array
oned=np.array([3,45,234,32])
oned[3]

32

In [230]:
# indexing operators
# Getting the row and column using row and column access

twod[1,3]


7

In [ ]:

# how do you find the element in the last row and last column?

In [231]:
# no of brackets indicate the dimension
# using : to access ranges

# if we want to access ranges of 1st two rows and all the columns
# Note that we still have the 2 dim array as a result

twod[0:2,]



array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [72]:
# if we want to access ranges of 1st two columns.
# Note that we still have the 2 dim array as a result
twod[:,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [ ]:
#Suppose we want to make changes to the array below:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

#we want to change the (0,0),(1,3),(2,2) cells and increase it by 100

In [95]:
twod[[0,1,2],[0,3,2]]=twod[[0,1,2],[0,3,2]]+100

twod

array([[100,   1,   2,   3],
       [  4,   5,   6, 107],
       [  8,   9, 110,  11]])

In [97]:
# We can also do the following
new_twod=np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])
rws=np.arange(3)
col=[0,3,2]

In [98]:
new_twod[rws,col]=new_twod[rws,col]+100
print(new_twod)

[[100   1   2   3]
 [  4   5   6 107]
 [  8   9 110  11]]


In [102]:
# 3d array
threed=np.arange(24).reshape(2,3,4)
threed


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [103]:
# how to get the 11 and 20 from the array
threed[[0,1],[2,2],[3,0]]


array([11, 20])

In [108]:
# Boolean indexing
# creating a new 2d array
n1=np.arange(20,40).reshape(5,4)
n1


array([[20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39]])

In [110]:
n1>30

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [113]:
n1[n1>30]

array([31, 32, 33, 34, 35, 36, 37, 38, 39])

# Some builtins methods of arrays


In [234]:
np.ones([4,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [121]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [124]:
np.eye((3))


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [128]:
np.full((2,2),5)

array([[5, 5],
       [5, 5]])

In [219]:
# Generating one random integers between two limits
np.random.randint(10,100)


15

In [220]:
# Generating 10 random integers between two limits
np.random.randint(5,100,10)

array([62, 68, 20, 45, 75, 99, 52, 59, 14, 76])

In [141]:
y=np.array([[21,34,56,25],[3,56,36,87],[35,12,46,87]])
y

array([[21, 34, 56, 25],
       [ 3, 56, 36, 87],
       [35, 12, 46, 87]])

In [142]:
# Indices of maximum values in the array
y.argmax()


7

In [143]:
# along an axis axis=0 is the vertical axis
y.argmax(axis=0)

array([2, 1, 0, 1], dtype=int64)

In [144]:
# along the horizontal axis (axis=1)
y.argmin(axis=1)

array([0, 0, 1], dtype=int64)

In [147]:
# Sorting the array if you dont provide the axis, then the default is axis=1
y.sort()
y

array([[21, 25, 34, 56],
       [ 3, 36, 56, 87],
       [12, 35, 46, 87]])

In [149]:
y.sort(axis=0)
y

array([[ 3, 25, 34, 56],
       [12, 35, 46, 87],
       [21, 36, 56, 87]])

In [150]:
# Transpose
y.T

array([[ 3, 12, 21],
       [25, 35, 36],
       [34, 46, 56],
       [56, 87, 87]])

In [151]:
# We can check the shape after transpose
y.T.shape

(4, 3)

In [166]:
# Transposing a 3d array
three=np.arange(24).reshape(2,3,4)
print(three)
three.shape

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


(2, 3, 4)

In [167]:
tr=three.T
tr.shape

(4, 3, 2)

In [170]:
# Suppose we dont want to transpose it completely, we can use swapaxes to do so
z=three.swapaxes(0,1)
print(z.shape)
print(z)

(3, 2, 4)
[[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]


Converting a multidimensional array into a single dim array


Flatten and ravel are 2 methods to do this with a minor difference:
Flatten returns a copy, while ravel returns a view of the orignal numpy array
Ravel is usually faster, since we dont have to copy the array


In [236]:
# Creating a 3*4 array
arr1=np.arange(12).reshape(3,4)
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [237]:
arr1.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [238]:
arr1.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

# Mathematical operations

We have addition, vector and scalar product also


In [181]:
a=np.array([[3,2,4],[11,4,8]])
b=np.array([[11,12,5],[2,9,1]])
print(a)
print(b)

[[ 3  2  4]
 [11  4  8]]
[[11 12  5]
 [ 2  9  1]]


In [173]:
# Element wise addition
a+b

array([[14, 14,  9],
       [13, 13,  9]])

In [196]:
np.add(a,b)

array([[14, 14,  9],
       [13, 13,  9]])

In [177]:
# Element wise subtraction
a-b

array([[ -8, -10,  -1],
       [  9,  -5,   7]])

In [185]:
np.subtract(a,b)

array([[ -8, -10,  -1],
       [  9,  -5,   7]])

In [187]:
# Element wise Multiplication
a*b

array([[33, 24, 20],
       [22, 36,  8]])

In [188]:
np.multiply(a,b)

array([[33, 24, 20],
       [22, 36,  8]])

In [189]:
# Element wise Division
a/b

array([[0.27272727, 0.16666667, 0.8       ],
       [5.5       , 0.44444444, 8.        ]])

In [190]:
np.divide(a,b)

array([[0.27272727, 0.16666667, 0.8       ],
       [5.5       , 0.44444444, 8.        ]])

In [194]:
# inner product
m1=np.array([[10,12],[5,6]])

m2=np.array([[7,4],[3,2]])
print(m1)
print(m2)

[[10 12]
 [ 5  6]]
[[7 4]
 [3 2]]


In [193]:
np.dot(m1,m2)

array([[106,  64],
       [ 53,  32]])

In [200]:
e=np.arange(100,150)
e

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149])

In [201]:
e.dtype

dtype('int32')

In [205]:
e.prod()

0

BROADCASTING
Numpy can treat arrays of different shapes during arithmetic operations.
if two arrays are of same shape, then it is easy to do operations.
However, if they are of different shapes, then also we can do the operations.
The smaller array is broadcast to the size of the bigger array so we can do the operations


In [226]:
a1=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
b1=np.array([10,11,12])
print(a1)
print(b1)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[10 11 12]


In [227]:
a1+b1

array([[11, 13, 15],
       [14, 16, 18],
       [17, 19, 21],
       [20, 22, 24]])

In [211]:
# Deep copy and shallow copy
org=np.array([3,4,5,6])

In [213]:
# Copying the orginal into a new object
new=org

In [215]:
# changing the new object at an index 1.
# Making changes in the new array
new[1]=400
new

array([  3, 400,   5,   6])

In [217]:
"""We see that whatever changes we make to the new array is also made at the original array,
since the data at the original location is also changed."""
# This is called a shallow copy
org

array([  3, 400,   5,   6])

In [218]:
# Instead of using the orignal object, create a copy of the object
org=np.array([3,4,5,6])
new=org.copy()
new[1]=400
print(new)
print(org)


[  3 400   5   6]
[3 4 5 6]
